[[nodes]]
id = "JM"
user_id = 1
hostname = "imac"
email = "redacted@node.invalid"
clone_path = "/home/joe/ai/aida-monitor"
name = "imac-joe-jm"
user = "joe"
registered = "2026-09-19T17:55:46.252822595Z"
